# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Author < Formula
  desc ""
  homepage ""
  version "0.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Pianoopera/author/releases/download/v0.0.8/author_Darwin_arm64.tar.gz"
      sha256 "55da932f441fd953b975d2531535bc5cba3b967baa32fdd49f9b252cea54dfbd"

      def install
        bin.install "author"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Pianoopera/author/releases/download/v0.0.8/author_Darwin_x86_64.tar.gz"
      sha256 "7d35e34d017ad05621c080e3e3348a9b46048234c2ebb87280545e3d71744d6b"

      def install
        bin.install "author"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Pianoopera/author/releases/download/v0.0.8/author_Linux_arm64.tar.gz"
      sha256 "6374d9b1e7c7c4788585ce21aec796ee96d565c69c0667c9de46814efff2d940"

      def install
        bin.install "author"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Pianoopera/author/releases/download/v0.0.8/author_Linux_x86_64.tar.gz"
      sha256 "18a37b9328e57c5f70dac532e57dd47593ac55242a121e5fa322550ae4b2d903"

      def install
        bin.install "author"
      end
    end
  end
end
