# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Author < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Pianoopera/author/releases/download/v0.1.1/author_Darwin_arm64.tar.gz"
      sha256 "ef08d8cd04e3cfb4dc5fd5c407f262ad8780226812b61ea7b34d103ed5f72725"

      def install
        bin.install "author"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Pianoopera/author/releases/download/v0.1.1/author_Darwin_x86_64.tar.gz"
      sha256 "594fecb48ba7b673769c9cf5bade29e9aaa101924172325b98efa9b51ed56f00"

      def install
        bin.install "author"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Pianoopera/author/releases/download/v0.1.1/author_Linux_arm64.tar.gz"
      sha256 "50d29fbf12eab7ec2ae9e8f25ce53d19356a02730332c41d3dec74e3da840cab"

      def install
        bin.install "author"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Pianoopera/author/releases/download/v0.1.1/author_Linux_x86_64.tar.gz"
      sha256 "6bfb0d66c84f123807bdf144fedf2095fdb186caf83af8c5e48b94c17c99442f"

      def install
        bin.install "author"
      end
    end
  end
end
