# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotionSwallow < Formula
  desc ""
  homepage ""
  version "0.3.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Pianoopera/notion-swallow/releases/download/v0.3.2/notion-swallow-v0.3.2-aarch64-apple-darwin.tar.gz"
      sha256 "f173dd2b3aabed02e8e243ff713415f1fe1dd374e77df9a91235bee1362bf925"

      def install
        bin.install "notion-swallow-v0.3.2-aarch64-apple-darwin" => "notion-swallow"
      end
    end
  end
end
