# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RfNotion < Formula
  desc ""
  homepage ""
  version "0.2.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Pianoopera/request-format-for-notion/releases/download/v0.2.1/rf-notion-v0.2.1-aarch64-apple-darwin"
      sha256 "ef9156ff1d2e5a09c146e768ef1dbb11955a54b94cc31e10d5868fa593ee501f"

      def install
        bin.install "rf-notion"
      end
    end
  end
end
